type DefaultPublicMemoryItem = {
  id: string;
  scope: 'public';
  kind: 'manual';
  status: 'active';
  source: 'manual';
  stageId: string;
  title: string;
  text: string;
  sourceReferences: [];
  confidence: number;
  createdAt: number;
  updatedAt: number;
};

type DefaultPublicMemoryDefinition = {
  title: string;
  text: string;
};

type DefaultCoursePublicMemoryInput = {
  id: string;
  name?: string | null;
  courseCode?: string | null;
  tags?: readonly string[] | null;
};

const MAT136_PUBLIC_MEMORY_UPDATED_AT = Date.parse('2026-05-20T00:00:00.000Z');
const MAT102_PUBLIC_MEMORY_UPDATED_AT = Date.parse('2026-06-01T00:00:00.000Z');

const mat136CoursePublicMemory: DefaultPublicMemoryDefinition = {
  title: 'MAT136 课程知识地图',
  text: [
    '## 课程知道的知识点',
    '- Riemann sum：用分割、采样点和矩形面积和近似曲线下方面积。',
    '- Riemann integrability：当 mesh 变细且所有合法采样方式趋向同一个极限时，函数可黎曼积分。',
    '- Definite integral：把黎曼和极限、有向面积和净变化统一到定积分符号中。',
    '- FTC II：用反导函数计算定积分，核心形式是 F(b) - F(a)。',
    '- FTC I：面积函数和变上限积分的求导，遇到复合上限时要乘以上限导数。',
    '- u-substitution：把复合函数积分看成反向链式法则，处理变量、du、上下限和回代。',
    '- inverse / trig substitution：针对 sqrt(a^2 - x^2)、sqrt(a^2 + x^2)、sqrt(x^2 - a^2) 选择 sin、tan、sec 代换。',
    '- integration by parts：把乘积法则反过来使用，按 u、dv、du、v 管理剩余积分。',
    '- area and volume applications：用 slicing、washer、shell 等方式把几何量写成积分。',
    '',
    '## 讲解重点',
    '- 课程主线不是单个公式堆叠，而是“面积近似 -> 极限定义 -> 计算工具 -> 换元/分部技巧 -> 应用建模”。',
    '- 每节笔记本都要先讲它解决什么问题，再讲公式；例如换元法解决复合函数，分部积分解决乘积结构。',
    '- 反复训练学生从题目结构判断方法：是 Riemann sum 翻译、FTC 计算、u-sub、trig-sub，还是 integration by parts。',
    '- 对定积分题要同时检查符号、上下限、几何含义和代数计算，避免只把积分当作机械反导。',
    '- 对应用题强调建模步骤：画变量、写截面积或壳体表达式、确定 bounds，再积分。',
    '',
    '## 笔记本覆盖关系',
    '| 笔记本 | 覆盖知识点 | 讲解重点 |',
    '| --- | --- | --- |',
    '| 黎曼积分 | partition、sample point、Riemann sum、mesh、integrability | 从矩形近似面积走到可积定义 |',
    '| 定积分 | signed area、properties、FTC II、Riemann sum conversion、FTC I | 把面积、极限和反导计算接起来 |',
    '| 换元法 | u、du、变量替换、定积分上下限 | 识别内层函数和外层导数影子 |',
    '| 逆换元法 | 三角代换、配方、回代、定义域 | 用形状选择 sin / tan / sec |',
    '| 分部积分 | u dv、du、v、多次分部、ln x、反三角函数 | 选择 u 和 dv，让剩余积分更简单 |',
    '| 面积与体积 | slicing、washer、shell、几何积分 | 先建模，再计算积分 |',
  ].join('\n'),
};

const mat136PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'nb-mat136-riemann-integral-week1-20260518135718': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 黎曼积分从矩形近似面积出发，把分割、采样点和面积求和统一起来。',
      '- 分割 P、采样点 c_i、子区间宽度 Δx_i 与求和表达式 Σ f(c_i)Δx_i。',
      '- 左端点、右端点、中点等常见采样规则。',
      '- 单调函数下左/右黎曼和的高估和低估关系。',
      '- mesh 趋近 0 时，黎曼和极限若不依赖采样点，就定义为黎曼积分。',
      '',
      '## 讲解重点',
      '- 按“分割区间、选采样点、加矩形面积、取极限”的流程讲清黎曼积分。',
      '- 区分某一次黎曼和近似值与真正的定积分极限。',
      '- 强调采样点可以变，但可积函数在分割变细时会收敛到同一个面积。',
      '- 用图像和表格例题训练学生把文字条件翻译成求和式。',
    ].join('\n'),
  },
  'nb-mat136-definite-integral-week1-20260518150500': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 定积分作为黎曼和极限，也可以表示有向面积和净变化。',
      '- 有向面积的正负号、积分上下限方向和区间可加性。',
      '- 定积分基本性质：线性、常数倍、区间拆分和比较直觉。',
      '- 微积分基本定理第二部分：用反导函数计算定积分。',
      '- 黎曼和与定积分符号之间的互相转换。',
      '- 微积分基本定理第一部分、面积函数、变上限积分和链式法则。',
      '',
      '## 讲解重点',
      '- 把定积分同时讲成三种面孔：面积、极限、反导计算工具。',
      '- 先建立符号和几何意义，再进入 FTC 的计算捷径。',
      '- 重点训练从 Riemann sum 极限识别积分区间、被积函数和 dx。',
      '- 对变上限积分强调“先求导外层面积函数，再乘以上限导数”。',
    ].join('\n'),
  },
  'nb-mat136-substitution-week2-20260518183518': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 换元法是反向链式法则，用 u 把复合函数积分化简。',
      '- 选择 u、计算 du，并处理差一个常数或负号的情况。',
      '- 换元后不能留下原变量 x，需要把所有部分都改写成 u。',
      '- 定积分换元时，上下限也要随变量一起改变。',
      '- 函数缩放型换元和没有现成公式时的结构识别。',
      '',
      '## 讲解重点',
      '- 每道题都按四个问题讲：u 选什么、du 是什么、是否还有 x、上下限怎么办。',
      '- 用例题集中处理常数倍、负号和残留变量这些最常见错误。',
      '- 对不定积分强调最后换回 x；对定积分强调换上下限后可以不换回。',
      '- 让学生先找“里面的函数”和“外面的导数影子”，再动手计算。',
    ].join('\n'),
  },
  'nb-mat136-inverse-substitution-week2-v2-20260519174000': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 普通 u-substitution 在根号二次式中为什么会卡住。',
      '- 三角代换把根号形状转成三角恒等式可以处理的结构。',
      '- 三类根号形状和代换规则：a^2 - x^2、a^2 + x^2、x^2 - a^2。',
      '- 配方后识别形状、换上下限、回代和定义域检查。',
      '- sin、tan、sec 代换背后的几何直觉。',
      '',
      '## 讲解重点',
      '- 先讲“为什么需要逆换元”，再给代换表，避免学生机械套公式。',
      '- 把根号形状和单位圆/直角三角形图像绑定起来。',
      '- 对每类代换都强调它消掉根号的那一步恒等式。',
      '- 用多个例题展示从诊断形状到完成积分的稳定流程。',
    ].join('\n'),
  },
  'nb-mat136-integration-by-parts-week2-v2-20260519151624': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 分部积分作为乘积法则的积分版：∫ u dv = uv - ∫ v du。',
      '- 选择 u 和 dv 的原则：u 求导变简单，dv 可以直接积分。',
      '- 典型题型：x cos x、ln x、需要多次分部的积分。',
      '- 进阶题型：先换元再分部的 ∫ x^3 cos(x^2) dx，以及反三角函数 ∫ arctan x dx。',
      '- 公式推导、角色表、剩余积分的难度判断。',
      '- 一次分部不够时，重复使用分部积分并整理结果。',
      '',
      '## 讲解重点',
      '- 用“为什么换元不够”引出分部积分，再从乘积法则推导公式。',
      '- 每题先做角色选择，不急着计算，训练学生解释为什么这样选。',
      '- 对 ln x 强调把它看成 ln x · 1，并令 dv = dx。',
      '- 对重复分部题强调过程管理：每一步都要让剩余积分更可控。',
      '- 对 PDF 补充例题强调先判断结构：能先消内层就先换元，剩下乘积再分部。',
    ].join('\n'),
  },
};

const cpsc107PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'nb-cpsc107-racket-basics-week1-20260519024537': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Racket 的基本阅读方式：一切都是表达式，表达式会被求值为 value。',
      '- 前缀表达式、operator / operands、primitive operators 和 built-in functions。',
      '- 求值规则：从左到右、从里到外，每一步只化简一个表达式。',
      '- Boolean 值、and / or / not 规则，以及短路求值。',
      '- String、Image、Number、Boolean 等 primitive data 的类型区别和常见操作。',
      '- 函数定义、函数调用求值、参数绑定、global constants、if 和 cond。',
      '',
      '## 讲解重点',
      '- 训练学生读代码时先问：这个表达式的 operator 是什么，operands 是什么，最后会得到什么值。',
      '- 用逐步化简展示 Racket 的求值顺序，尤其强调短路求值和分支只执行其中一路。',
      '- 反复区分不同 primitive data 类型，避免把 String、Number、Image 混用。',
      '- 把数学函数翻译成 Racket 函数时，强调参数只是占位符，调用时才用实际值替换。',
      '- 对 if / cond 重点讲清判断顺序、分支选择和没有被选中的分支不会求值。',
      '',
      '## Racket 代码参考',
      '```racket',
      ';; prefix notation: operator first, operands after',
      '(check-expect (+ (* 2 3) (- 10 4)) 12)',
      '',
      '(define TAX-RATE 0.13)',
      '(define PASS-LINE 50)',
      '(define HONOURS-LINE 85)',
      '(define MAX-MISSED 2)',
      '',
      '(@signature Number -> Number)',
      ';; produce total price after tax',
      '(check-expect (total 100) 113)',
      ';(define (total price) 0) ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (total price)',
      '   (... price)))',
      '',
      '(define (total price)',
      '  (* price (+ 1 TAX-RATE)))',
      '',
      '(@signature Number -> String)',
      ';; produce "negative", "zero", or "positive" for n',
      '(check-expect (sign -2) "negative")',
      '(check-expect (sign 0) "zero")',
      '(check-expect (sign 3) "positive")',
      ';(define (sign n) "zero") ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (sign n)',
      '   (... n)))',
      '',
      '(define (sign n)',
      '  (cond [(< n 0) "negative"]',
      '        [(= n 0) "zero"]',
      '        [else "positive"]))',
      '',
      '(@signature Number Number Boolean -> String)',
      ';; produce final standing from grade, missed labs, and project status',
      '(check-expect (standing 92 0 true) "honours")',
      '(check-expect (standing 92 3 true) "incomplete")',
      '(check-expect (standing 48 0 true) "fail")',
      '(check-expect (standing 92 0 false) "incomplete")',
      ';(define (standing grade missed project-submitted?) "fail") ;stub',
      '',
      '(@template-origin Number Number Boolean)',
      '(@template',
      ' (define (standing grade missed project-submitted?)',
      '   (... grade missed project-submitted?)))',
      '',
      '(define (standing grade missed project-submitted?)',
      '  (cond [(or (not project-submitted?)',
      '             (> missed MAX-MISSED))',
      '         "incomplete"]',
      '        [(and (>= grade HONOURS-LINE)',
      '              (<= missed 1))',
      '         "honours"]',
      '        [(>= grade PASS-LINE) "pass"]',
      '        [else "fail"]))',
      '',
      ';; Stepper trace: MAX-MISSED is used when first OR question is false.',
      ';; (standing 92 3 true)',
      ';; => (cond [(or (not true)',
      ';;               (> 3 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          [(and (>= 92 HONOURS-LINE)',
      ';;                (<= 3 1))',
      ';;           "honours"]',
      ';;          [(>= 92 PASS-LINE) "pass"]',
      ';;          [else "fail"])',
      ';; => (cond [(or false (> 3 2))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [(or false true)',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [true',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => "incomplete"',
      '',
      ';; Stepper trace: if first OR question is true, second is skipped.',
      ';; (standing 92 0 false)',
      ';; => (cond [(or (not false)',
      ';;               (> 0 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [(or true (> 0 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => "incomplete"',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-htdf-htdd-week2-20260519043417': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- HTDF 是设计函数的固定流程：function name、signature、purpose、examples、stub、template、function body。',
      '- Signature 声明函数 consume / produce 的数据类型，目前常见类型包括 Number、String、Boolean、Image，并可细分 Integer、Natural。',
      '- Purpose 必须一行内说明输入和输出，通常不超过 80 个字符；examples 用 check-expect 表达预期行为。',
      '- Stub 是带正确函数名、参数个数和返回类型的空壳函数；Number 返回 0，String 返回 ""，Image 返回 empty-image。',
      '- HTDD 用来设计数据，包括 @htdd、interp、examples、@dd-template-rules 和由数据形状推导出的 template。',
      '- Atomic non-distinct / atomic distinct 的区别：普通 Number/String/Boolean/Image/Interval 走 non-distinct，固定值如 "red"、false、empty 走 distinct。',
      '- 自定义数据类型可以用更有语义的名字，例如 CityName 比 String 更能说明函数真正接受什么。',
      '- One-of 包含 enumeration 和 itemization；enumeration 是有限固定值，itemization 是不同类型或形状的组合。',
      '- Compound data 用 define-struct 表示一个值同时拥有多个字段，并用 selector 取出字段。',
      '',
      '## 讲解重点',
      '- 先让学生填 HTDF 七步，再打开 Racket 写代码，避免直接跳到 body。',
      '- 用 circle-area 讲清 HTDF 的完整结构：signature、purpose、check-expect、stub、template、body 每一项都服务于函数实现。',
      '- 用 next-color 对比“裸代码”和“加 HTDF 后的代码”，说明 design record 能让函数意图和测试更容易读懂。',
      '- 对 stub 要强调只有一个分号，并且 dummy result 必须符合 signature 的输出类型。',
      '- 讲 HTDD 时反复把数据类型、template rule 和 template body 连起来，提醒学生 template 不是凭感觉写的。',
      '- 讲 enumeration 时强调 normal enumerations 不用 else；讲 itemization 时强调 cond question 要先用 type predicate guard，最后一问用 else。',
      '- 讲 compound data 时强调它不是 one-of：compound 的字段同时存在，selector 是 template 的核心。',
      '',
      '## PDF 表格整理',
      '',
      '### HTDF 七步',
      '| 顺序 | HTDF 部分 | 讲解记忆点 |',
      '| --- | --- | --- |',
      '| 1 | Function Name | 函数名要让人看出这个函数大概做什么。 |',
      '| 2 | Signature | 写出函数 consume 什么类型的数据、produce 什么类型的数据。 |',
      '| 3 | Purpose | 用一行说明函数输入和输出，不超过两句话，通常不超过 80 个字符。 |',
      '| 4 | Examples | 用 3 到 5 个 check-expect 展示函数应该如何工作。 |',
      '| 5 | Stub | 只写对函数名、参数数量和返回类型，用正确类型的 dummy result。 |',
      '| 6 | Template | 根据数据形状选择逻辑框架，不直接凭感觉写 body。 |',
      '| 7 | Function Body | 最后才写真正执行的函数逻辑。 |',
      '',
      '### Stub dummy result 对照',
      '| Output type | Stub result |',
      '| --- | --- |',
      '| Number / Integer / Natural | 0 |',
      '| String | "" |',
      '| Image | empty-image |',
      '',
      '### HTDD 基础类型表',
      '| Type of Data | dd-template-rules | Template body |',
      '| --- | --- | --- |',
      '| Number | atomic-non-distinct | (... c) |',
      '| String | atomic-non-distinct | (... c) |',
      '| Boolean | atomic-non-distinct | (... c) |',
      '| Image | atomic-non-distinct | (... c) |',
      '| Interval | atomic-non-distinct | (... c) |',
      '| "red" | atomic-distinct | (...) |',
      '| false | atomic-distinct | (...) |',
      '| empty | atomic-distinct | (...) |',
      '',
      '### One-of 条件判断表',
      '| Type of Data | dd-template-rules | Template | Cond question |',
      '| --- | --- | --- | --- |',
      '| Number | atomic-non-distinct | (... c) | (number? x) |',
      '| String | atomic-non-distinct | (... c) | (string? x) |',
      '| Boolean | atomic-non-distinct | (... c) | (boolean? x) |',
      '| Image | atomic-non-distinct | (... c) | (image? x) |',
      '| Interval | atomic-non-distinct | (... c) | (and (<= 1 x) (<= x 10)) |',
      '| "red" | atomic-distinct | (...) | (string=? x "red") |',
      '| false | atomic-distinct | (...) | (false? x) |',
      '| empty | atomic-distinct | (...) | (empty? x) |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdf circle-area)',
      '(@signature Number -> Number)',
      ';; calculate the area of a circle by given radius',
      '(check-expect (circle-area 0) 0)',
      '(check-within (circle-area 1) 3.14 0.01)',
      ';(define (circle-area r) 0) ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (circle-area r)',
      '   (... r)))',
      '',
      '(define (circle-area r)',
      '  (* 3.14 (* r r)))',
      '',
      '(@htdf next-color)',
      '(@signature Natural -> Natural)',
      ';; produce the next color of a traffic light',
      '(check-expect (next-color 0) 2)',
      '(check-expect (next-color 1) 0)',
      '(check-expect (next-color 2) 1)',
      ';(define (next-color c) 0) ;stub',
      '',
      '(@template-origin Natural)',
      '(@template',
      ' (define (next-color c)',
      '   (... c)))',
      '',
      '(define (next-color c)',
      '  (if (= c 0)',
      '      2',
      '      (if (= c 1)',
      '          0',
      '          1)))',
      '',
      '(@htdd SeatNumber)',
      ';; SeatNumber is an Integer',
      ';; interp. seat number in a row, 1 and 32 are aisle seats',
      '(define START 1)',
      '(define MID 16)',
      '(define END 32)',
      '',
      '(@dd-template-rules atomic-non-distinct)',
      '(define (fn-for-seatnumber sn)',
      '  (... sn))',
      '',
      ';; LetterGrade is one of:',
      ';; - "A"',
      ';; - "B"',
      ';; - "C"',
      ';; interp. The letter grade in the course',
      ';; Examples are redundant for enumerations.',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-distinct',
      '                    atomic-distinct)',
      '',
      '(define (fn-for-letter-grade lg)',
      '  (cond [(string=? lg "A") (...)]',
      '        [(string=? lg "B") (...)]',
      '        [(string=? lg "C") (...)]))',
      '',
      '(@htdd CountDown)',
      ';; CountDown is one of:',
      ';; - false',
      ';; - Natural[1, 10]',
      ';; - "complete"',
      ';; interp.',
      ';;   false means countdown is not started',
      ';;   Natural[1, 10] means countdown is running',
      ';;   "complete" means countdown is completed',
      '(define CD1 false)',
      '(define CD2 1)',
      '(define CD3 10)',
      '(define CD4 "complete")',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-non-distinct',
      '                    atomic-distinct)',
      '',
      '(define (fn-for-count-down c)',
      '  (cond [(false? c) (...)]',
      '        [(and (number? c) (<= 1 c) (<= c 10)) (... c)]',
      '        [else (...)]))',
      '',
      '(@htdd Ball)',
      '(define-struct ball (x y))',
      ';; Ball is (make-ball Number Number)',
      ';; interp. a ball at position x, y',
      '(define BALL-1 (make-ball 6 10))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-ball b)',
      '  (... (ball-x b)',
      '       (ball-y b)))',
      '',
      '(@htdd Student)',
      '(define-struct student (id name major))',
      ';; Student is (make-student Number String String)',
      ";; interp. a student's information",
      ';;         id is the id of a student',
      ';;         name is the student name',
      ";;         major is the student's major",
      '(define SD1 (make-student 101 "Andy" "CS"))',
      '(define SD2 (make-student 301 "Oscar" "Math"))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-student s)',
      '  (... (student-id s)',
      '       (student-name s)',
      '       (student-major s)))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-ref-self-ref-week4-20260519140849': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Reference 指一个数据定义包含另一个已经定义好的数据定义，例如 Game 里面有 Ball。',
      '- Reference template 的核心动作：遇到自定义数据字段时，不直接拆字段内部，而是调用对应的 helper template。',
      '- Self-reference 指数据定义递归引用自己；ListOfX 的 rest 仍然是 ListOfX，是最典型的 self-ref。',
      '- Racket list 的基本构造和读取：empty、cons、list、quasiquote、first、second、third、fourth、rest。',
      '- 常见 list operations：length、member?、append、reverse、empty?。',
      '- ListOf primitive data 的模板：empty 分支是 atomic-distinct，cons 分支是 compound，rest 分支是 self-ref。',
      '- List of compound data 的模板：first 是 ref，调用 compound item 的 helper。',
      '- 在 List of compound 里，rest 是 self-ref，要递归调用当前 template。',
      '- 考试型递归数据定义包括 Waldo、Peat 这类 one-of itemization，需要同时识别 atomic-distinct、compound、self-ref。',
      '',
      '## 讲解重点',
      '- 用 Ball / Game 先讲 reference：Game 的 ball 字段已经是 Ball，所以 template 里写 fn-for-ball。',
      '- 用 cons 链讲 self-reference：empty 是 base case，(cons X ListOfX) 是 recursive case。',
      '- 讲 first / rest 时强调：first 拿当前元素，rest 拿剩余同类型 list，因此 rest 对应递归调用。',
      '- 讲 ListOfString 时让学生看到它和 ListOfInteger 只有元素类型变了，模板结构不变。',
      '- 讲 ListOfBook、ListOfDot 时强调同时出现 ref 和 self-ref：first 调 helper，rest 递归。',
      '- 做 Waldo / Peat 题时先逐行标 rule，再写 cond；每个分支必须有合适的 type predicate 或 distinct-value 判断。',
      '- 最后一类 atomic-distinct 分支通常可以用 else，但前面的 string 分支要先 guard，避免对非 string 调 string=?。',
      '',
      '## PDF 表格整理',
      '',
      '### Reference 与 Self-Reference',
      '| 概念 | 数据形状 | Template 动作 | PDF 例子 |',
      '| --- | --- | --- | --- |',
      '| Reference | 字段引用另一个已定义数据 | 调用对应 helper template | Game contains Ball |',
      '| Self-reference | 数据定义引用自己 | 对递归字段调用当前 template | rest of ListOfInteger |',
      '| Reference + self-reference | list 元素是 compound/custom data | first 调 helper，rest 递归 | ListOfDot |',
      '',
      '### List 操作记忆表',
      '| Operation | 用途 | PDF 例子含义 |',
      '| --- | --- | --- |',
      '| cons | 往 list 前面加一个元素 | (cons 1 (cons 2 empty)) |',
      '| list | 简便构造 list | (list 1 2 3) |',
      '| first / second / third / fourth | 读取指定位置元素 | (first L7) 产生 1 |',
      '| rest | 去掉第一个元素，得到剩余 list | (rest L7) 产生 (list 2 3 4 5 6 7) |',
      '| length | 计算 list 长度 | (length L7) 产生 7 |',
      '| member? | 判断元素是否在 list 中 | (member? 2 L7) 产生 true |',
      '| append | 合并两个 list | append 两个 list 得到更长 list |',
      '| reverse | 反转 list 顺序 | (reverse (list 1 2 3 4)) 产生 (list 4 3 2 1) |',
      '| empty? | 判断 list 是否为空 | (empty? empty) 产生 true |',
      '',
      '### Template rule 对照表',
      '| 数据定义形状 | dd-template-rules | Template 写法重点 |',
      '| --- | --- | --- |',
      '| compound only | compound | 用 selector 取每个字段 |',
      '| compound with custom field | compound + ref | 自定义字段调用 helper，如 fn-for-ball |',
      '| ListOf primitive | one-of + atomic-distinct + compound + self-ref | empty 分支结束；first 直接使用；rest 递归 |',
      '| List of compound | one-of + atomic-distinct + compound + ref + self-ref | first 调 helper；rest 递归 |',
      '| Recursive itemization | one-of + compound + self-ref + atomic-distinct | 先识别分支，再在递归字段调用当前 template |',
      '',
      '## Racket 代码参考',
      '```racket',
      ';; Reference: Game contains Ball.',
      '(@htdd Ball)',
      '(define-struct ball (x y))',
      ';; Ball is (make-ball Number Number)',
      ';; interp. a ball at position x, y',
      '(define BALL-1 (make-ball 6 10))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-ball b)',
      '  (... (ball-x b)',
      '       (ball-y b)))',
      '',
      '(@htdd Game)',
      '(define-struct game (ball score))',
      ';; Game is (make-game Ball Number)',
      ';; interp. current game state with the ball and score',
      '(define GAME-1 (make-game (make-ball 1 5) 2))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-game g)',
      '  (... (fn-for-ball (game-ball g))',
      '       (game-score g)))',
      '',
      ';; Self-reference: rest of ListOfInteger is another ListOfInteger.',
      '(@htdd ListOfInteger)',
      ';; ListOfInteger is one of:',
      ';; - empty',
      ';; - (cons Integer ListOfInteger)',
      ';; interp. a list of integers',
      '(define LOI0 empty)',
      '(define LOI1 (cons 212 (cons -98 (cons 3 empty))))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-loi loi)',
      '  (cond [(empty? loi) (...)]',
      '        [else',
      '         (... (first loi)',
      '              (fn-for-loi (rest loi)))]))',
      '',
      '(@htdd ListOfString)',
      ';; ListOfString is one of:',
      ';; - empty',
      ';; - (cons String ListOfString)',
      ';; interp. a list of strings',
      '(define LOS-1 empty)',
      '(define LOS-2 (cons "a" empty))',
      '(define LOS-3 (cons "b" (cons "c" empty)))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-los los)',
      '  (cond [(empty? los) (...)]',
      '        [else',
      '         (... (first los)',
      '              (fn-for-los (rest los)))]))',
      '',
      ';; List of compound data: first is a reference, rest is self-reference.',
      '(@htdd Book)',
      '(define-struct book (title auth year genre))',
      ';; Book is (make-book String String Natural String)',
      ';; interp. a book with title, author, year, and genre',
      '(define B1',
      '  (make-book "The Hate U Give"',
      '             "Angie Thomas"',
      '             2017',
      '             "Young Adult"))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-book b)',
      '  (... (book-title b)',
      '       (book-auth b)',
      '       (book-year b)',
      '       (book-genre b)))',
      '',
      '(@htdd ListOfBook)',
      ';; ListOfBook is one of:',
      ';; - empty',
      ';; - (cons Book ListOfBook)',
      ';; interp. a list of books',
      '(define LOB0 empty)',
      '(define LOB1 (cons B1 empty))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lob lob)',
      '  (cond [(empty? lob) (...)]',
      '        [else',
      '         (... (fn-for-book (first lob))',
      '              (fn-for-lob (rest lob)))]))',
      '',
      '(@htdd Dot)',
      '(define-struct dot (x y))',
      ';; Dot is (make-dot Integer Integer)',
      ';; interp. a dot on the screen, with x and y coordinates',
      '(define D1 (make-dot 10 30))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-dot d)',
      '  (... (dot-x d)',
      '       (dot-y d)))',
      '',
      '(@htdd ListOfDot)',
      ';; ListOfDot is one of:',
      ';; - empty',
      ';; - (cons Dot ListOfDot)',
      ';; interp. a list of dots',
      '(define LOD1 empty)',
      '(define LOD2 (cons (make-dot 10 20)',
      '                   (cons (make-dot 3 6) empty)))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lod lod)',
      '  (cond [(empty? lod) (...)]',
      '        [else',
      '         (... (fn-for-dot (first lod))',
      '              (fn-for-lod (rest lod)))]))',
      '```',
      '',
      '## 考试题型模板',
      '```racket',
      '(@htdd Waldo)',
      '(define-struct fie (a b))',
      '(define-struct foe (c d))',
      ';; Waldo is one of:',
      ';; - "fee"',
      ';; - "floo"',
      ';; - (make-fie Integer String)',
      ';; - (make-foe Number Waldo)',
      ';; - true',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-distinct',
      '                    compound',
      '                    compound',
      '                    self-ref',
      '                    atomic-distinct)',
      '(define (fn-for-waldo w)',
      '  (cond [(and (string? w) (string=? w "fee")) (...)]',
      '        [(string? w) (...)]',
      '        [(fie? w)',
      '         (... (fie-a w)',
      '              (fie-b w))]',
      '        [(foe? w)',
      '         (... (foe-c w)',
      '              (fn-for-waldo (foe-d w)))]',
      '        [else (...)]))',
      '',
      '(@htdd Peat)',
      '(define-struct crim (k d))',
      '(define-struct rudz (s b))',
      ';; Peat is one of:',
      ';; - (make-crim Integer Peat)',
      ';; - (make-rudz String Number)',
      ';; - false',
      ';; - "zap"',
      '',
      '(@dd-template-rules one-of',
      '                    compound',
      '                    self-ref',
      '                    compound',
      '                    atomic-distinct',
      '                    atomic-distinct)',
      '(define (fn-for-peat p)',
      '  (cond [(crim? p)',
      '         (... (crim-k p)',
      '              (fn-for-peat (crim-d p)))]',
      '        [(rudz? p)',
      '         (... (rudz-s p)',
      '              (rudz-b p))]',
      '        [(false? p) (...)]',
      '        [else (...)]))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-recursion-bst-imagegen-20260522': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Recursion 的核心是把当前问题拆成 base case 和 smaller problem；数学递归里要看 recurrence 需要几个 base cases。',
      '- List recursion 里 empty 是 base case，(rest loi) 是同类型的更小问题，template 来自 ListOfInteger 的 self-reference。',
      '- Helper function 来自 template：当一个数据定义引用另一个自定义数据时，外层函数只拆外层，内层交给对应 helper。',
      '- Package / Gift / Dimensions 例题展示 compound、one-of、reference 三种数据定义如何配合。',
      '- Tree 是无环的层级结构，包含 root、parent、sibling、children、ancestor、descendant、depth、height、subtree 等术语。',
      '- Binary tree 每个节点最多两个子树；BST 在 binary tree 基础上加入左小右大的 invariant。',
      '- BST lookup 根据 target 和当前 node key 的比较结果，只进入左子树或右子树，不需要遍历整棵树。',
      '',
      '## 讲解重点',
      '- 讲递归时先问停止条件是什么，再问每一步如何让问题变小。',
      '- 讲 list template 时强调 first 代表当前元素，rest 代表剩余同类型 list，所以 rest 对应 recursive call。',
      '- 讲 helper 时不要说成“为了省代码”，而要说成“模板要求”：Package contains Gift，所以 Package 函数调用 Gift helper。',
      '- 讲 package-required-dims 时把职责拆开：Package 层只取 contents；Gift 层根据 ball / block 决定尺寸。',
      '- 讲 tree 术语时要把 depth 和 height 区分开：depth 从 root 往下数，height 从当前 node 往最远 leaf 数。',
      '- 讲 BST 时先建立 invariant，再解释为什么 lookup-key 的每一步都能丢掉半边搜索空间。',
      '',
      '## PDF 表格整理',
      '',
      '### Recursion 与 List Template',
      '| 数据形状 | Base case | Recursive case | Template 动作 |',
      '| --- | --- | --- | --- |',
      '| Natural recursion | 0 或 1 等停止值 | n 的更小值 | 对更小的 Natural 调用当前函数 |',
      '| Fibonacci recursion | recurrence 要访问 n - 1 和 n - 2，所以需要两个 base cases | 两个 recursive calls | 每条递归分支都必须能停到 base case |',
      '| ListOfInteger | empty | (cons Integer ListOfInteger) | first 处理当前整数，rest 递归 |',
      '',
      '### Package / Gift 职责表',
      '| 数据定义 | 数据形状 | Template 重点 | 真实函数职责 |',
      '| --- | --- | --- | --- |',
      '| Gift | ball 或 block | cond 分 ball? / block? | ball 用 diameter，block 直接取三边 |',
      '| Package | to 和 contents | contents 是 Gift，所以调 helper | 取出 contents 交给 gift-required-dims |',
      '| Dimensions | w、l、h 三个字段 | selector 取三边 | 作为结果数据被 make-dims 产生 |',
      '',
      '### Tree 术语表',
      '| 术语 | 记忆点 |',
      '| --- | --- |',
      '| root | 树的起点，没有 parent |',
      '| parent / children | 直接上一级和直接下一级节点 |',
      '| sibling | 同一个 parent 的 children 互为 sibling |',
      '| ancestor / descendant | 从 root 到当前点路径上的上游节点；以及当前点往下的所有后代 |',
      '| depth | 从 root 到该 node 的边数，root depth 为 0 |',
      '| height | 从该 node 到最远 leaf 的边数 |',
      '| subtree | 以某个 node 为 root，包含它和所有 descendants 的树 |',
      '',
      '### BST Lookup 判断表',
      '| 当前情况 | 结果或下一步 | 原因 |',
      '| --- | --- | --- |',
      '| bst 是 false | false | 空树里找不到 target |',
      '| target = node key | true | 当前节点就是目标 |',
      '| target < node key | 搜 left subtree | BST invariant 保证右边都更大 |',
      '| target > node key | 搜 right subtree | BST invariant 保证左边都更小 |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdd ListOfInteger)',
      ';; ListOfInteger is one of:',
      ';; - empty',
      ';; - (cons Integer ListOfInteger)',
      ';; interp. a list of integers',
      '(define LOI0 empty)',
      '(define LOI1 (list 3 1 2 4 7))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-loi loi)',
      '  (cond [(empty? loi) (...)]',
      '        [else',
      '         (... (first loi)',
      '              (fn-for-loi (rest loi)))]))',
      '',
      '(@htdf multiply-odds)',
      '(@signature ListOfInteger -> Integer)',
      ';; produce the product of all odd integers in loi',
      '(check-expect (multiply-odds empty) 1)',
      '(check-expect (multiply-odds (list 2 4 6)) 1)',
      '(check-expect (multiply-odds (list 3 1 2 4 7)) 21)',
      ';(define (multiply-odds loi) 1) ;stub',
      '',
      '(@template-origin ListOfInteger)',
      '(@template',
      ' (define (multiply-odds loi)',
      '   (cond [(empty? loi) (...)]',
      '         [else',
      '          (... (first loi)',
      '               (multiply-odds (rest loi)))])))',
      '',
      '(define (multiply-odds loi)',
      '  (cond [(empty? loi) 1]',
      '        [else',
      '         (if (odd? (first loi))',
      '             (* (first loi)',
      '                (multiply-odds (rest loi)))',
      '             (multiply-odds (rest loi)))]))',
      '',
      '(@htdd Gift)',
      '(define-struct ball (radius))',
      '(define-struct block (width length height))',
      ';; Gift is one of:',
      ';; - (make-ball Natural)',
      ';; - (make-block Natural Natural Natural)',
      ';; interp. a gift. A ball has a radius; a block has dimensions.',
      ';; CONSTRAINT: all measurements are greater than 0',
      '(define G-BALL (make-ball 2))',
      '(define G-BLOCK (make-block 3 4 5))',
      '',
      '(@dd-template-rules one-of',
      '                    compound',
      '                    compound)',
      '(define (fn-for-gift g)',
      '  (cond [(ball? g) (... (ball-radius g))]',
      '        [(block? g)',
      '         (... (block-width g)',
      '              (block-length g)',
      '              (block-height g))]))',
      '',
      '(@htdd Package)',
      '(define-struct package (to contents))',
      ';; Package is (make-package String Gift)',
      ';; interp. a package recipient and the gift inside',
      '(define P-BALL (make-package "Gregor" G-BALL))',
      '(define P-BLOCK (make-package "Emily" G-BLOCK))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-package p)',
      '  (... (package-to p)',
      '       (fn-for-gift (package-contents p))))',
      '',
      '(@htdd Dimensions)',
      '(define-struct dims (w l h))',
      ';; Dimensions is (make-dims Number Number Number)',
      ';; interp. width, length, and height of a box in centimeters',
      '',
      '(@htdf package-required-dims gift-required-dims)',
      '(@signature Package -> Dimensions)',
      '(@signature Gift -> Dimensions)',
      ';; produce required internal package dimensions for p',
      ';; produce required internal package dimensions for g',
      '(check-expect (package-required-dims P-BALL) (make-dims 4 4 4))',
      '(check-expect (package-required-dims P-BLOCK) (make-dims 3 4 5))',
      ';(define (package-required-dims p) (make-dims 1 1 1)) ;stub',
      ';(define (gift-required-dims g) (make-dims 1 1 1)) ;stub',
      '',
      '(@template-origin Package)',
      '(@template',
      ' (define (package-required-dims p)',
      '   (... (package-to p)',
      '        (gift-required-dims (package-contents p)))))',
      '',
      '(define (package-required-dims p)',
      '  (gift-required-dims (package-contents p)))',
      '',
      '(@template-origin Gift)',
      '(@template',
      ' (define (gift-required-dims g)',
      '   (cond [(ball? g) (... (ball-radius g))]',
      '         [(block? g)',
      '          (... (block-width g)',
      '               (block-length g)',
      '               (block-height g))])))',
      '',
      '(define (gift-required-dims g)',
      '  (cond [(ball? g)',
      '         (make-dims (* 2 (ball-radius g))',
      '                    (* 2 (ball-radius g))',
      '                    (* 2 (ball-radius g)))]',
      '        [(block? g)',
      '         (make-dims (block-width g)',
      '                    (block-length g)',
      '                    (block-height g))]))',
      '```',
      '',
      '## BST 代码参考',
      '```racket',
      '(@htdd BST)',
      '(define-struct node (key left right))',
      ';; BST is one of:',
      ';; - false',
      ';; - (make-node Integer BST BST)',
      ';; interp. false means empty tree; node stores a key and subtrees',
      ';; INVARIANT: all keys in left are less than key,',
      ';;            all keys in right are greater than key,',
      ';;            and no key appears twice',
      '(define BST0 false)',
      '(define BST1 (make-node 1 false false))',
      '(define BST4 (make-node 4 false (make-node 7 false false)))',
      '(define BST3 (make-node 3 BST1 BST4))',
      '(define BST42',
      '  (make-node 42',
      '             (make-node 27 (make-node 14 false false) false)',
      '             (make-node 50 false false)))',
      '(define BST10 (make-node 10 BST3 BST42))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref',
      '                    self-ref)',
      '(define (fn-for-bst bst)',
      '  (cond [(false? bst) (...)]',
      '        [else',
      '         (... (node-key bst)',
      '              (fn-for-bst (node-left bst))',
      '              (fn-for-bst (node-right bst)))]))',
      '',
      '(@htdf lookup-key)',
      '(@signature Integer BST -> Boolean)',
      ';; produce true if bst contains target key',
      '(check-expect (lookup-key 10 BST0) false)',
      '(check-expect (lookup-key 1 BST10) true)',
      '(check-expect (lookup-key 50 BST10) true)',
      '(check-expect (lookup-key 99 BST10) false)',
      ';(define (lookup-key target bst) false) ;stub',
      '',
      '(@template-origin BST)',
      '(@template',
      ' (define (lookup-key target bst)',
      '   (cond [(false? bst) (...)]',
      '         [else',
      '          (... target',
      '               (node-key bst)',
      '               (lookup-key target (node-left bst))',
      '               (lookup-key target (node-right bst)))])))',
      '',
      '(define (lookup-key target bst)',
      '  (cond [(false? bst) false]',
      '        [(= target (node-key bst)) true]',
      '        [(< target (node-key bst))',
      '         (lookup-key target (node-left bst))]',
      '        [else',
      '         (lookup-key target (node-right bst))]))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-trees-mutual-recursion-imagegen-20260522': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Reference classification 包括 R、SR、MR：R 是普通引用，SR 是自引用，MR 是多个数据定义形成引用环。',
      '- Function recursion classification 包括 NH、NR、NMR：NH 是 helper call，NR 是函数直接调用自己，NMR 是多个函数互相调用形成环。',
      '- 判断 MR / NMR 时要把数据定义或函数调用画成图，看是否存在从一个点走出去又回到同一个点的 cycle。',
      '- Arbitrary-branch tree 可以用 Node 和 ListOfNode 两个互相引用的数据定义表示。',
      '- Node 函数负责当前 node 的 value 和 children；ListOfNode 函数负责 empty / first / rest。',
      '- Mutually recursive functions 必须成对设计：一个函数处理 Node，一个函数处理 ListOfNode。',
      '- sum--node / sum--lon 展示树上所有 value 求和；greater-than--node / greater-than--lon 展示树上筛选并 append 结果。',
      '- Course / ListOfCourse 是正式命名模式：course-dependents 是 ListOfCourse，所以 all-course-numbers 也要拆成两个函数。',
      '',
      '## 讲解重点',
      '- 先判断最容易的 self-reference：ListOfX 的 rest 指回 ListOfX，通常是 SR。',
      '- 再找环：如果 A 包含 B，B 又经由某条路径包含 A，这些箭头属于 mutual reference。',
      '- 区分 data graph 和 function call graph：数据里的 MR 通常会导出函数里的 NMR，但标注时要看题目问的是哪一种。',
      '- 讲 tree traversal 时用固定口令：node 处理当前值，lon 处理一串孩子。',
      '- 讲 sum 时强调 empty 的 identity 是 0；讲 greater-than 时强调 empty 的 identity 是 empty，兄弟子树结果用 append 合并。',
      '- 讲 Course 例题时把 current course number 用 cons 放前面，把 dependents 的结果交给 ListOfCourse helper。',
      '',
      '## PDF 表格整理',
      '',
      '### Reference / Recursion 标签表',
      '| 标签 | 全称 | 判断方式 | PDF 例子 |',
      '| --- | --- | --- | --- |',
      '| R | reference | 只引用另一个数据定义，没有形成环 | Employee 到 ListOfGrant；Baz 到 Zorker |',
      '| SR | self-reference | 数据定义直接或通过 rest 指回自己 | ListOfEmployee 的 rest；ListOfFoo 的 rest |',
      '| MR | mutual-reference | 两个或多个数据定义形成环 | Employee 和 ListOfEmployee；Foo、Baz、ListOfFoo |',
      '| NH | natural helper | 函数调用另一个 helper，没有递归环 | fn-for-baz 调 fn-for-zorker |',
      '| NR | natural recursion | 函数直接调用自己 | fn-for-lof 调 fn-for-lof |',
      '| NMR | natural mutual recursion | 多个函数互相调用形成环 | fn-for-foo、fn-for-baz、fn-for-lof 形成 cycle |',
      '',
      '### PDF 例题答案整理',
      '| 题目 | 最容易先判 | Mutual-reference 环 | 普通 reference |',
      '| --- | --- | --- | --- |',
      '| Employee / Grant | D、F 是 SR | A、C 是 MR，因为 Employee 和 ListOfEmployee 互相包含 | B、E 是 R |',
      '| Foo / Baz / Zorker / ListOfFoo | E 是 SR | A、C、D 是 MR，因为 Foo、Baz、ListOfFoo 形成环 | B 是 R |',
      '',
      '### Tree 函数职责表',
      '| 函数层级 | 输入类型 | 负责什么 | 常见组合方式 |',
      '| --- | --- | --- | --- |',
      '| node function | Node | 当前 value，加上 children 的结果 | 使用 node selector，然后调用 lon helper |',
      '| lon function | ListOfNode | empty / first / rest | empty 给 identity；first 调 node helper；rest 递归 |',
      '| sum traversal | Number result | 把所有值加起来 | empty -> 0，组合用 + |',
      '| filter traversal | List result | 收集满足条件的 value | empty -> empty，兄弟结果用 append |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdd Node ListOfNode)',
      '(define-struct node (val children))',
      ';; Node is (make-node Number ListOfNode)',
      ';; interp. a tree node with a value and a list of children',
      ';; ListOfNode is one of:',
      ';; - empty',
      ';; - (cons Node ListOfNode)',
      ';; interp. a list of tree nodes',
      '(define N2 (make-node 2 empty))',
      '(define N3 (make-node 3 empty))',
      '(define N5 (make-node 5 empty))',
      '(define N7 (make-node 7 empty))',
      '(define T1 (make-node 1 (list N2 N7)))',
      '(define T2 (make-node 4 (list T1 N3 N5)))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-node n)',
      '  (... (node-val n)',
      '       (fn-for-lon (node-children n))))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lon lon)',
      '  (cond [(empty? lon) (...)]',
      '        [else',
      '         (... (fn-for-node (first lon))',
      '              (fn-for-lon (rest lon)))]))',
      '',
      '(@htdf sum--node sum--lon)',
      '(@signature Node -> Number)',
      '(@signature ListOfNode -> Number)',
      ';; produce sum of all node values in n',
      ';; produce sum of all node values in lon',
      '(check-expect (sum--lon empty) 0)',
      '(check-expect (sum--node N2) 2)',
      '(check-expect (sum--node T2) 22)',
      ';(define (sum--node n) 0) ;stub',
      ';(define (sum--lon lon) 0) ;stub',
      '',
      '(@template-origin Node)',
      '(@template',
      ' (define (sum--node n)',
      '   (... (node-val n)',
      '        (sum--lon (node-children n)))))',
      '',
      '(define (sum--node n)',
      '  (+ (node-val n)',
      '     (sum--lon (node-children n))))',
      '',
      '(@template-origin ListOfNode)',
      '(@template',
      ' (define (sum--lon lon)',
      '   (cond [(empty? lon) (...)]',
      '         [else',
      '          (... (sum--node (first lon))',
      '               (sum--lon (rest lon)))])))',
      '',
      '(define (sum--lon lon)',
      '  (cond [(empty? lon) 0]',
      '        [else',
      '         (+ (sum--node (first lon))',
      '            (sum--lon (rest lon)))]))',
      '',
      '(@htdd ListOfNumber)',
      ';; ListOfNumber is one of:',
      ';; - empty',
      ';; - (cons Number ListOfNumber)',
      ';; interp. a list of numbers',
      '',
      '(@htdf greater-than--node greater-than--lon)',
      '(@signature Node Number -> ListOfNumber)',
      '(@signature ListOfNode Number -> ListOfNumber)',
      ';; produce values in n that are greater than threshold',
      ';; produce values in lon that are greater than threshold',
      '(check-expect (greater-than--lon empty 3) empty)',
      '(check-expect (greater-than--node N2 3) empty)',
      '(check-expect (greater-than--node T2 3) (list 4 7 5))',
      ';(define (greater-than--node n threshold) empty) ;stub',
      ';(define (greater-than--lon lon threshold) empty) ;stub',
      '',
      '(@template-origin Node)',
      '(define (greater-than--node n threshold)',
      '  (if (> (node-val n) threshold)',
      '      (cons (node-val n)',
      '            (greater-than--lon (node-children n) threshold))',
      '      (greater-than--lon (node-children n) threshold)))',
      '',
      '(@template-origin ListOfNode)',
      '(define (greater-than--lon lon threshold)',
      '  (cond [(empty? lon) empty]',
      '        [else',
      '         (append (greater-than--node (first lon) threshold)',
      '                 (greater-than--lon (rest lon) threshold))]))',
      '```',
      '',
      '## Course / ListOfCourse 代码参考',
      '```racket',
      '(@htdd Course ListOfCourse)',
      '(define-struct course (number credits dependents))',
      ';; Course is (make-course Natural Natural ListOfCourse)',
      ';; interp. a course number, credits, and dependent courses',
      ';; ListOfCourse is one of:',
      ';; - empty',
      ';; - (cons Course ListOfCourse)',
      ';; interp. a list of courses',
      '(define C313 (make-course 313 3 empty))',
      '(define C317 (make-course 317 3 empty))',
      '(define LOC313-317 (list C313 C317))',
      '(define C213 (make-course 213 4 LOC313-317))',
      '',
      '(@htdd ListOfNatural)',
      ';; ListOfNatural is one of:',
      ';; - empty',
      ';; - (cons Natural ListOfNatural)',
      ';; interp. a list of natural numbers',
      '',
      '(@htdf all-course-numbers--course all-course-numbers--loc)',
      '(@signature Course -> ListOfNatural)',
      '(@signature ListOfCourse -> ListOfNatural)',
      ';; produce all course numbers in c and its dependents',
      ';; produce all course numbers in loc and their dependents',
      '(check-expect (all-course-numbers--loc empty) empty)',
      '(check-expect (all-course-numbers--course C313) (list 313))',
      '(check-expect (all-course-numbers--course C213) (list 213 313 317))',
      ';(define (all-course-numbers--course c) empty) ;stub',
      ';(define (all-course-numbers--loc loc) empty) ;stub',
      '',
      '(@template-origin Course)',
      '(define (all-course-numbers--course c)',
      '  (cons (course-number c)',
      '        (all-course-numbers--loc (course-dependents c))))',
      '',
      '(@template-origin ListOfCourse)',
      '(define (all-course-numbers--loc loc)',
      '  (cond [(empty? loc) empty]',
      '        [else',
      '         (append (all-course-numbers--course (first loc))',
      '                 (all-course-numbers--loc (rest loc)))]))',
      '```',
    ].join('\n'),
  },
};

const mat102PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'mat102-sets-propositions-proof-v2': {
    title: 'MAT102 集合与命题证明入口',
    text: [
      '## 来源范围',
      '- 适用于 MAT102 第一本文字/图片 notebook：01 - 集合与命题。',
      '- 来源是 queue/MAT102/02SetsAndPropositions (1).pdf、queue 生成稿，以及当前 proof-first 四角恢复图片笔记本。',
      '- 后续答疑、出题和续写这本 notebook 时，优先按“定义展开 -> 元素任取 -> 逻辑翻译 -> 回到目标”的证明动作组织答案。',
      '',
      '## 老师讲了什么',
      '- 这本不是单纯复习集合符号，而是在建立证明课的第一套语言：对象、集合、成员关系、包含关系和真假判断。',
      '- 集合必须是无序、互异、定义明确的对象收集；well-defined 的重点是能判断一个对象到底属不属于集合。',
      '- 集合构造式要能展开：a 属于 {x in U : P(x)} 等价于 a 在 U 中并且 P(a) 成立。',
      '- 并、交、差、补集、笛卡尔积都要先翻译成“x 属于哪里”的逻辑句子，再做计算或证明。',
      '- 命题有确定真值；谓词含自由变量，只有代入具体对象或加上量词后才变成可判真的句子。',
      '- AND、OR、NOT 和真值表是后续证明逻辑等价、否定语句和处理量词的基础。',
      '',
      '## 标准证明动作',
      '- 证明 S subset T：任取 x in S，展开 S 的定义或已知条件，目标是推出 x in T。',
      '- 证明集合相等：分别证明 A subset B 和 B subset A，两条包含路缺一不可。',
      '- 证明 A subset A union B：任取 x in A，由并集定义得到 x in A 或 x in B，因此 x in A union B。',
      '- 证明 A intersection B subset A：任取 x in A intersection B，由交集定义得到 x in A 且 x in B，于是 x in A。',
      '- 证明 A union B = B 且已知 A subset B：先证 A union B subset B，遇到 x in A 的分支时调用 A subset B；再证 B subset A union B。',
      '- 证明两个集合构造式相等：从一边任取元素，把存在的整数参数代数改写成另一边需要的形式，再反向做一次。',
      '- 证明逻辑等价：列出所有真值组合，逐列计算两边，最后比较结果列。',
      '',
      '## 易错点',
      '- 说“看起来在里面”不是证明；必须指出任取对象、已知条件、定义依据和目标。',
      '- 忘记全集 U 时，补集没有完整含义。',
      '- 把有序对当普通集合会丢掉顺序信息；A x B 通常不同于 B x A。',
      '- 把 A subset A intersection B 当作总成立命题是方向错误；总成立的是 A intersection B subset A。',
      '- 把谓词当命题会导致真假未定；变量没固定时不能直接给出真值。',
      '- 数学里的 OR 是包含式或：至少一个为真即可，两个都真也为真。',
    ].join('\n'),
  },
  'nb-mat102-zh-induction-i-20260519': {
    title: 'MAT102 归纳法证明格式与老师步骤',
    text: [
      '## 来源范围',
      '- 适用于 MAT102 的 Induction I notebook，来源是 queue/MAT102/10InductionI-1.pdf 和已确认的 10 页 imagegen/recover 图片笔记本。',
      '- 后续答疑、出题和续写这本 notebook 时，优先按这里的证明格式和老师步骤组织答案。',
      '',
      '## 老师讲了什么',
      '- 本节主线是：用有限的起点检查和推进规则，覆盖无限多个编号命题。',
      '- 普通归纳不是“检查很多例子”，而是证明 base case 成立，并证明从 P(k) 能推出 P(k+1)。',
      '- 归纳假设只能临时使用已声明的旧命题，不能提前使用目标命题。',
      '- 强归纳允许使用前面所有已经证明过的情形，适合新情况会退回多个旧情况的题。',
      '- 结构归纳把对象看成由 basis elements 和 constructors 生成；证明要沿着生成规则走。',
      '',
      '## 证明格式',
      '- 写普通归纳证明时，先定义命题 P(n) 和 n 的适用范围。',
      '- Base case 要明确检查起点，不能只说显然。',
      '- Induction step 要写：令 k 为任意满足范围的整数，并假设 P(k) 成立；目标是证明 P(k+1)。',
      '- 推导中每次使用归纳假设都要能指出旧命题如何进入新命题。',
      '- 结尾要写：由数学归纳法，P(n) 对范围内所有 n 成立。',
      '- 若起点不是 1 或步长不是 1，要先说明链条覆盖哪些编号；步长为 2 时通常需要分别覆盖奇偶链。',
      '- 强归纳证明要写清允许使用的旧情况范围，例如所有小于等于 k 的情形。',
      '',
      '## 老师给出的标准步骤',
      '- 整除归纳题先把“整除”翻译成整数倍等式，再代入归纳步骤。',
      '- 求和归纳题把前 k+1 项拆成“前 k 项的旧和”加“新的一项”，再用归纳假设替换旧和。',
      '- 不等式归纳题先写出 k+1 目标式，再把它改写到可以调用 k 层假设的形状。',
      '- L 形铺砖题用构造式归纳：把大棋盘分成四块小棋盘，中间放一块 L 形砖，让每块都变成同类小问题。',
      '- 多个 base cases 不是形式要求，而是为了保证后续每次退回时都落在已经覆盖的范围。',
      '',
      '## 易错点',
      '- 只验几个 n 不是证明。',
      '- 把 P(k+1) 当成已经成立，是偷用结论。',
      '- 忘记写 base case 会让整条归纳链没有起点。',
      '- 在强归纳里不说明旧情况范围，会让证明不可审计。',
      '- 在结构归纳里只验基本对象，不验每一种 constructor，证明不完整。',
    ].join('\n'),
  },
};

function isMat136Course(course: DefaultCoursePublicMemoryInput): boolean {
  const courseCode = course.courseCode?.trim().toUpperCase();
  if (courseCode === 'MAT136' || courseCode === 'MAT 136') return true;
  const haystack = [course.name, course.courseCode, ...(course.tags || [])]
    .filter((value): value is string => typeof value === 'string')
    .join(' ')
    .toUpperCase();
  return /\bMAT\s*136\b/.test(haystack);
}

export function getDefaultNotebookPublicMemories(stageId: string): DefaultPublicMemoryItem[] {
  const definition =
    mat136PublicMemories[stageId] ??
    cpsc107PublicMemories[stageId] ??
    mat102PublicMemories[stageId];
  if (!definition) return [];

  return [
    {
      id: `default-public-memory:${stageId}:knowledge-focus`,
      scope: 'public',
      kind: 'manual',
      status: 'active',
      source: 'manual',
      stageId,
      title: definition.title,
      text: definition.text,
      sourceReferences: [],
      confidence: 1,
      createdAt:
        mat102PublicMemories[stageId] !== undefined
          ? MAT102_PUBLIC_MEMORY_UPDATED_AT
          : MAT136_PUBLIC_MEMORY_UPDATED_AT,
      updatedAt:
        mat102PublicMemories[stageId] !== undefined
          ? MAT102_PUBLIC_MEMORY_UPDATED_AT
          : MAT136_PUBLIC_MEMORY_UPDATED_AT,
    },
  ];
}

export function getDefaultCoursePublicMemories(
  course: DefaultCoursePublicMemoryInput,
): DefaultPublicMemoryItem[] {
  const definition = isMat136Course(course) ? mat136CoursePublicMemory : null;
  if (!definition) return [];

  return [
    {
      id: `default-public-memory:course:${course.id}:knowledge-map`,
      scope: 'public',
      kind: 'manual',
      status: 'active',
      source: 'manual',
      stageId: course.id,
      title: definition.title,
      text: definition.text,
      sourceReferences: [],
      confidence: 1,
      createdAt: MAT136_PUBLIC_MEMORY_UPDATED_AT,
      updatedAt: MAT136_PUBLIC_MEMORY_UPDATED_AT,
    },
  ];
}

export function countDefaultCoursePublicMemories(course: DefaultCoursePublicMemoryInput): number {
  return getDefaultCoursePublicMemories(course).length;
}
