export type {
  NotebookContentBlock,
  NotebookContentContinuation,
  NotebookContentDocument,
  NotebookContentDisciplineStyle,
  NotebookContentGridLayout,
  NotebookContentLanguage,
  NotebookContentLayout,
  NotebookContentLayoutFamily,
  NotebookContentLayoutMode,
  NotebookContentLayoutTemplate,
  NotebookContentDensity,
  NotebookContentVisualRole,
  NotebookContentOverflowPolicy,
  NotebookContentPattern,
  NotebookContentVisualSlot,
  NotebookContentTextTemplate,
  NotebookContentTitleTone,
  NotebookContentBlockPlacement,
  NotebookContentProfile,
  NotebookContentProcessFlowBlock,
  NotebookContentProcessFlowContextItem,
  NotebookContentProcessFlowStep,
  NotebookContentLayoutCardsBlock,
  NotebookContentLayoutCardsItem,
  NotebookContentVisualBlock,
  NotebookContentSlot,
  NotebookContentStackLayout,
  NotebookContentTeachingFlow,
  NotebookSlideArchetype,
} from './schema';
export {
  notebookContentContinuationSchema,
  notebookContentDensitySchema,
  notebookContentDisciplineStyleSchema,
  notebookContentDocumentSchema,
  notebookContentLayoutFamilySchema,
  notebookContentLayoutSchema,
  notebookContentLayoutModeSchema,
  notebookContentLayoutTemplateSchema,
  notebookContentOverflowPolicySchema,
  notebookContentPatternSchema,
  notebookContentVisualRoleSchema,
  notebookContentVisualSlotSchema,
  notebookContentTextTemplateSchema,
  notebookContentTeachingFlowSchema,
  notebookContentTitleToneSchema,
  notebookContentBlockPlacementSchema,
  notebookContentSlotSchema,
  notebookContentProfileSchema,
  notebookSlideArchetypeSchema,
  parseNotebookContentDocument,
} from './schema';
export {
  SLOT_TEMPLATE_REGISTRY,
  getSlotOrder,
  getSlotTemplateSpec,
  type SlotTemplateSlotSpec,
  type SlotTemplateSpec,
} from './slot-template-registry';
export {
  buildNotebookContentDocumentFromInsert,
  buildNotebookContentDocumentFromText,
} from './builders';
export {
  compileSyntaraMarkupToNotebookDocument,
  extractSyntaraMarkup,
  parseSyntaraMarkup,
} from './markup';
export {
  inferNotebookContentProfileFromBlocks,
  inferNotebookContentProfileFromText,
  resolveNotebookContentProfile,
} from './profile';
export { renderNotebookContentToMarkdown } from './render-chat';
export {
  renderNotebookContentDocumentToSlide,
  assessNotebookContentDocumentForSlide,
  paginateNotebookContentDocument,
  validateNotebookContentDocumentArchetype,
  type NotebookSlideContentBudgetAssessment,
  type NotebookDocumentPaginationResult,
  type NotebookDocumentArchetypeValidation,
} from './slide-adapter';
export {
  shouldLockNotebookSemanticLayout,
  measureNotebookSemanticLayout,
  paginateNotebookSemanticLayout,
  renderNotebookSemanticPages,
  prepareNotebookSemanticLayout,
  type NotebookSemanticRenderedPage,
  type PrepareNotebookSemanticLayoutArgs,
  type PreparedNotebookSemanticLayout,
} from './semantic-layout';
export {
  estimateParagraphHeight,
  estimateParagraphStackHeight,
  estimateCharsPerLine,
  estimateParagraphHeightForWidth,
  estimateParagraphStackHeightForWidth,
  estimateWrappedLineCount,
  wrapTextToLines,
  measureHtmlHeightIfAvailable,
  measureParagraphBlock,
  measureBulletListBlock,
  measureParagraphHeightIfAvailable,
  estimateGridHeadingHeight,
  measureLayoutCardsLayout,
  estimateProcessFlowSummaryHeight,
  estimateProcessFlowStepCardHeight,
  estimateProcessFlowBlockHeight,
  assessExpandedBlockHeight,
  toRenderAwareBudgetHeight,
  assessPageUsage,
  calcSparsePenalty,
  getBaseBodyHeight,
  type LayoutCardsMeasurement,
  type MeasuredTextBlock,
  type MeasuredNotebookBlockHeight,
  type NotebookPageUsageEstimate,
  type NotebookMeasurementLayoutSettings,
} from './measure';
export { chemistryTextToHtml } from './chemistry';
